modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/quattage/mechano/issues"
license="LGPL v3"

[[mods]]
modId="mechano"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime 
version="${file.jarVersion}"
displayName="Mechano"
#updateJSONURL=""
displayURL="https://discord.gg/2HBUz75Dg6"
logoFile="logo.png"
#credits=""
authors="quattage"
description='''
Bringing Create polish to other mods.'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
