# Builds and deposits artifacts automatically. Based on Fabric's configs

name: test-build
on: [pull_request, push]

jobs:
  build:
    name: build artifact
    permissions: write-all
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        id: capture_artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/

      - name: create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}-${{ github.run_attempt }}
          release_name: test-release
          draft: false
          prerelease: true
          body: |
                THIS IS AN AUTOMATICALLY GENERATED PRE-RELEASE CONTAINING THE LATEST CHANGES.

      - name: download artifact
        id: download-artifact
        uses: actions/download-artifact@v3

      - name: push release assets
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.download-artifact.outputs.download-path}}/artifact/mechano-1.19.2-0.1
          asset_name: artifact.zip
          asset_content_type: application/zip


      