# Displays commit information in a discord webhook

name: Write Info
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: grab commit information
    permissions: write-all
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: get date/time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
