# Pushes the latest successful build to release

name: test-release
on:
  workflow_run:
    workflows: ["test-build"]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/libs/
          GITHUB_TOKEN: ${{ secrets.MUH_KEY }}